In [1]:
import pandas as pd
import numpy as np

In [16]:
train_source1 = pd.read_csv("../../student_resource/dataset/train/train_source1.tsv", sep="\t")
train_source2 = pd.read_csv("../../student_resource/dataset/train/train_source2.tsv", sep="\t")
train_source3 = pd.read_csv("../../student_resource/dataset/train/train_source3.tsv", sep="\t")
train_ground_truth = pd.read_csv("../../student_resource/dataset/train/train_ground_truth.tsv", sep="\t")

In [15]:
train_source1.head(5)

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [17]:
display(train_source2.sample(3))
display(train_source3.tail(5))

,entity_id,business_name,business_address,country
320206,S2-532368893,Fontenot Vanguard Managed Riverside,"25677 149ST ST, ISSAQUAH, WA",US
4497301,S2-240169884,Bangalore Jettl LLP,"PLOT 103. 24, 3RD CROSS, BEML LAYOUT BASAVESHW...",India
2249336,S2-520695135,ATLANTIC TRADING PRIVATE LIMITED,"Y-1-3/3LOHA MANDI NARAINA, NEW DELHI, Delhi",India

,entity_id,business_name,business_address,country
5285598,S3-549653960,Vip Solutions,NaN,India
5285599,S3-45212707,Cornerstone Nippon,"Paula Drive, Arkansas, N Little Rock",US
5285600,S3-257390113,Legacy Piedmont,"Portland, Maine, Forest Park",US
5285601,S3-97881155,Pranava Meribl Trust,"235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...",India
5285602,S3-864344230,The Trusted Defense Products Inc,NaN,US

In [18]:
train_ground_truth.head(5)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...